name: Continuous Integration

on: pull_request

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check out composer dependencies
        run: |
          composer update && composer install

      - name: Run phpunit
        run: |
          vendor/bin/phpunit --debug -c phpunit.xml
